version: '2'

services:
    web:
        image: nginx:1.13.5-alpine
        ports:
            - "80:80"
            - "8876:8876"
            - "8877:8877"
        volumes:
            - ./www:/www
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:7.1.10-fpm-alpine3.4
        volumes:
            - ./www:/www
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - code-network

networks:
    code-network:
        driver: bridge

